CREATE TABLE `admitad_postback` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`offer_id` integer,
	`offer_name` text,
	`subid` text,
	`action` text,
	`action_id` text,
	`subid1` text,
	`subid2` text,
	`subid3` text,
	`subid4` text,
	`payment_sum` integer,
	`payment_status` text,
	`reward_ready` text,
	`order_id` integer,
	`order_sum` integer,
	`click_time` integer,
	`time` integer,
	`convertion_time` integer,
	`type` text
);
